In [36]:
import pandas as pd
import numpy as np
df=pd.read_csv("data.csv")
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1

In [35]:
print(df.describe())
print(df.index)
print(df.columns)

              Age         BMI     Glucose     Insulin        HOMA      Leptin  \
count  114.000000  114.000000  114.000000  114.000000  114.000000  114.000000
mean    57.359649   27.114035   98.026316   10.004000    2.703846   26.578302
std     16.221982    5.042753   22.653395   10.105777    3.667335   19.348325
min     24.000000   18.000000   60.000000    2.432000    0.467409    4.311000
25%     45.000000   23.000000   86.000000    4.367000    0.931358   12.279025
50%     56.000000   27.000000   92.500000    5.924500    1.380939   19.587300
75%     71.000000   31.000000  102.000000   10.887750    2.798224   37.688100
max     89.000000   38.000000  201.000000   58.460000   25.050342   90.280000

       Adiponectin    Resistin        MCP.1  Classification
count   114.000000  114.000000   114.000000      114.000000
mean      9.957554   14.835159   538.446816        1.561404
std       6.378908   12.452810   347.341360        0.498406
min       1.656020    3.210000    45.843000        1.000000
25%       5.466508    6.899263   272.780000        1.000000
50%       8.352692   10.827740   477.904000        2.000000
75%      11.735717   18.155563   702.677000        2.000000
max      36.060000   82.100000  1698.440000        2.000000
Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
      dtype='int64', length=114)
Index(['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin',
       'Resistin', 'MCP.1', 'Classification'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             116 non-null    int64
 1   BMI             116 non-null    float64
 2   Glucose         116 non-null    int64
 3   Insulin         116 non-null    float64
 4   HOMA            116 non-null    float64
 5   Leptin          116 non-null    float64
 6   Adiponectin     116 non-null    float64
 7   Resistin        116 non-null    float64
 8   MCP.1           116 non-null    float64
 9   Classification  116 non-null    object
dtypes: float64(7), int64(2), object(1)
memory usage: 9.2+ KB

In [5]:
df.isnull()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
111,False,False,False,False,False,False,False,False,False,False
112,False,False,False,False,False,False,False,False,False,False
113,False,False,False,False,False,False,False,False,False,False
114,False,False,False,False,False,False,False,False,False,False
115,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

In [8]:
df.describe(include='all')

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
count,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64
mean,57.301724,27.582111,97.793103,10.012086,2.694988,26.615080,10.180874,14.725966,534.647000,NaN
std,16.112766,5.020136,22.525162,10.067768,3.642043,19.183294,6.843341,12.390646,345.912663,NaN
min,24.000000,18.370000,60.000000,2.432000,0.467409,4.311000,1.656020,3.210000,45.843000,NaN
25%,45.000000,22.973205,85.750000,4.359250,0.917966,12.313675,5.474283,6.881763,269.978250,NaN
50%,56.000000,27.662416,92.000000,5.924500,1.380939,20.271000,8.352692,10.827740,471.322500,NaN
75%,71.000000,31.241442,102.000000,11.189250,2.857787,37.378300,11.815970,17.755207,700.085000,NaN
max,89.000000,38.578759,201.000000,58.460000,25.050342,90.280000,38.040000,82.100000,1698.440000,NaN

In [9]:
df.dtypes

Age                 int64
BMI               float64
Glucose             int64
Insulin           float64
HOMA              float64
Leptin            float64
Adiponectin       float64
Resistin          float64
MCP.1             float64
Classification     object
dtype: object

In [10]:
df.shape

(116, 10)

In [11]:
df['Classification'] = df['Classification'].astype('category')

In [14]:
# Replace 'na' with actual NaN
df['Classification'] = df['Classification'].replace('na', np.nan)

# Drop rows with missing classification
df = df.dropna(subset=['Classification'])

In [18]:

df.loc[:, 'Classification'] = df['Classification'].astype(int)

In [19]:
# Step 5: (Optional) Convert categorical columns to numeric
df_encoded = pd.get_dummies(df, drop_first=True)

# Step 6: View the cleaned data
print(df_encoded.head())

   Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635

     MCP.1  Classification
0  417.114               1
1  468.786               1
2  554.697               1
3  928.220               1
4  773.920               1

In [26]:
#optional dont do if no

df['BMI'] = df['BMI'].astype('int')   
# Replace 'na' with actual NaN
df['BMI'] = df['BMI'].replace('na', np.nan)

# Drop rows with missing classification
df = df.dropna(subset=['BMI'])

In [27]:
df_encoded = pd.get_dummies(df, drop_first=True)

In [28]:
print(df_encoded.dtypes)

Age                 int64
BMI                 int32
Glucose             int64
Insulin           float64
HOMA              float64
Leptin            float64
Adiponectin       float64
Resistin          float64
MCP.1             float64
Classification      int32
dtype: object

In [37]:
df['Insulin']

0       2.707
1       3.115
2       4.498
3       3.226
4       3.549
        ...
111     3.330
112     4.530
113     5.730
114     2.820
115    19.910
Name: Insulin, Length: 116, dtype: float64

In [38]:
#optiona; in this way we can convert datatype
df['HOMA']=df['HOMA'].astype('int')

In [39]:
df.dtypes

Age                 int64
BMI               float64
Glucose             int64
Insulin           float64
HOMA                int32
Leptin            float64
Adiponectin       float64
Resistin          float64
MCP.1             float64
Classification     object
dtype: object